#!/bin/sh

check_status() {
    if [ $1 != 0 ]; then
        echo -e "\r\033[2K[\e[31mError\e[0m]\t$2 ...failed"
        exit 1
    else
        echo -e "\r\033[2K[\e[32mOK\e[0m]\t$2"
    fi
}

# echo -ne "[ ] Updating source lists...\n"
opkg update > /dev/null
check_status $? "Updating source lists"

BASEINSTALL="systemd busybox coreutils"
for B in $BASEINSTALL; do
    echo -ne "\r\033[2K[..]\tUpdating $B..."
    opkg install $B > /dev/null
    check_status $? "Update for $B"
done

echo -ne "\r\033[2K[..]\tUpdating system..."
opkg-upgrade.sh -f > /dev/null
check_status $? "System update"
